package com.example.Springbootdemo.pojo;

public class Appuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.id
     *
     * @mbg.generated Sun Oct 07 20:47:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.name
     *
     * @mbg.generated Sun Oct 07 20:47:34 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.description
     *
     * @mbg.generated Sun Oct 07 20:47:34 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.id
     *
     * @return the value of appuser.id
     *
     * @mbg.generated Sun Oct 07 20:47:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.id
     *
     * @param id the value for appuser.id
     *
     * @mbg.generated Sun Oct 07 20:47:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.name
     *
     * @return the value of appuser.name
     *
     * @mbg.generated Sun Oct 07 20:47:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.name
     *
     * @param name the value for appuser.name
     *
     * @mbg.generated Sun Oct 07 20:47:34 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.description
     *
     * @return the value of appuser.description
     *
     * @mbg.generated Sun Oct 07 20:47:34 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.description
     *
     * @param description the value for appuser.description
     *
     * @mbg.generated Sun Oct 07 20:47:34 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}